//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// UXStudio.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_UXSTUDIO_FORM               101
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_UXStudioTYPE                130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_MENU_VIEW_CONTEXT           311
#define IDD_PROPERTY                    312
#define IDB_TEXT_ALIGN_BOTTOM           314
#define IDB_TEXT_ALIGN_CENTER           315
#define IDB_TEXT_ALIGN_LEFT             316
#define IDB_TEXT_ALIGN_MIDDLE           317
#define IDB_TEXT_ALIGN_RIGHT            318
#define IDB_TEXT_ALIGN_TOP              319
#define IDD_MOVE_INDEX                  320
#define IDC_BUTTON1                     1000
#define IDC_STATIC_X                    1006
#define IDC_STATIC_X1                   1006
#define IDC_STATIC_Y                    1007
#define IDC_STATIC_Y1                   1007
#define IDC_STATIC_W                    1008
#define IDC_STATIC_H                    1009
#define IDC_STATIC_LABEL                1010
#define IDC_STATIC_FILL                 1011
#define IDC_STATIC_FILL_COLOR           1012
#define IDC_STATIC_X3                   1013
#define IDC_STATIC_FILL_OPACITY         1013
#define IDC_STATIC_STROKE               1014
#define IDC_STATIC_STROKE_COLOR         1015
#define IDC_STATIC_STROKE_OPACITY       1016
#define IDC_STATIC_STROKE_THICKNESS     1017
#define IDC_STATIC_ROUND                1018
#define IDC_STATIC_X2                   1019
#define IDC_STATIC_Y2                   1020
#define IDC_STATIC_CANVAS_SIZE          1021
#define IDC_STATIC_GRID_SIZE            1022
#define IDC_STATIC_ROUND0               1023
#define IDC_STATIC_ROUND1               1024
#define IDC_STATIC_ROUND2               1025
#define IDC_STATIC_ROUND3               1026
#define IDC_STATIC_CANVAS_SIZE_CX       1027
#define IDC_STATIC_CANVAS_SIZE_CY       1028
#define IDC_STATIC_GRID_SIZE_CX         1029
#define IDC_STATIC_ROUND7               1030
#define IDC_STATIC_GRID_SIZE_CY         1030
#define IDC_COMBO_FONT                  1031
#define IDC_STATIC_FONT_SIZE            1032
#define IDC_STATIC_FONT                 1033
#define IDC_CHECK_FONT_BOLD             1034
#define IDC_STATIC_FONT_WEIGHT          1034
#define IDC_CHECK_FONT_ITALIC           1035
#define IDC_STATIC_FONT_COLOR           1036
#define IDC_STATIC_TEXT_COLOR           1036
#define IDC_STATIC_FILL_OPACITY2        1037
#define IDC_STATIC_TEXT_OPACITY         1037
#define IDC_STATIC_TEXT_ALIGN           1038
#define IDC_RADIO_ALIGN_LEFT            1039
#define IDC_RADIO_ALIGN_CENTER          1040
#define IDC_RADIO_ALIGN_RIGHT           1041
#define IDC_STATIC_DESCRIPTION          1041
#define IDC_RADIO_VALIGN_TOP            1042
#define IDC_RADIO_ONLY_CURRENT          1042
#define IDC_RADIO_VALIGN_CENTER         1043
#define IDC_EDIT_NEW_INDEX              1043
#define IDC_RADIO_VALIGN_BOTTOM         1044
#define IDC_RADIO_INCLUDE_FOLLOWS       1044
#define IDC_STATIC_CANVAS_COLOR         1045
#define IDC_EDIT_NEW_INDEX2             1045
#define IDC_EDIT_END_INDEX              1045
#define IDC_STATIC_GRID_COLOR           1046
#define IDC_STATIC_IMAGE_PATH           1047
#define ID_VIEW_32771                   32771
#define ID_MENU_VIEW_SEND_TO_END        32772
#define ID_MENU_VIEW_SEND_TO_BACK       32773
#define ID_MENU_VIEW_SEND_TO_FORE       32774
#define ID_MENU_VIEW_SEND_TO_TOP        32775
#define ID_VIEW_32776                   32776
#define ID_MENU_VIEW_COPY               32777
#define ID_MENU_VIEW_PASTE              32778
#define ID_MENU_VIEW_SEND_TO_BOTTOM     32779
#define ID_VIEW_32780                   32780
#define ID_MENU_VIEW_LABEL_EDIT         32781
#define ID_VIEW_32782                   32782
#define ID_MENU_VIEW_DELETE             32783
#define ID_32784                        32784
#define ID_MENU_VIEW_SHOW_COORD         32785
#define ID_VIEW_32786                   32786
#define ID_MENU_VIEW_SORT               32787
#define ID_VIEW_32788                   32788
#define ID_MENU_VIEW_MOVE_INDEX         32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
